#ifndef BLACKPEARL_CONFIG_HPP
#define BLACKPEARL_CONFIG_HPP

#define BLACKPEARL_MAX_NUM_PIXELS 805306368
#define BLACKPEARL_MAX_NUM_FIELDS 100
#define BLACKPEARL_MAX_LMAX 16384
#define BLACKPEARL_MAX_MMAX 16384

#endif //BLACKPEARL_CONFIG_HPP
