#ifndef BLACKPEARL_VERSION_HPP
#define BLACKPEARL_VERSION_HPP

#define BLACKPEARL_VERSION_MAJOR 0
#define BLACKPEARL_VERSION_MINOR 1
#define BLACKPEARL_VERSION_PATCH 0


#endif // BLACKPEARL_VERSION_HPP
